/* h2 SQL Query */
-- 중복 테이블 방지
DROP TABLE if EXISTS member CASCADE;

-- 테이블 생성
CREATE TABLE member( 
	id BIGINT GENERATED BY default AS identity,
	name VARCHAR(255),
	primary key (id)
);

-- 맴버 주입
INSERT INTO member(
	name
) VALUES (
	'spring2'
);

-- 맴버 조회
SELECT *
  FROM member;
